export const Actions = {
  ADD_FRAME: 'ADD_FRAME',
  INCREMENT_COUNT: 'INCREMENT_COUNT',
  SELECT_FRAME: 'SELECT_FRAME',
  SET_COUNT: 'SET_COUNT',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
};

export default Actions;
